# Generated by Django 5.1.4 on 2024-12-20 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sales",
            old_name="sales_data",
            new_name="sales_date",
        ),
    ]
